USE [master]
GO
/****** Object:  Database [Cemet]    Script Date: 12/02/2013 12:35:13 ******/
CREATE DATABASE [Cemet] ON  PRIMARY 
( NAME = N'Cemet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cemet.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cemet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cemet_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Cemet] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cemet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Cemet] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Cemet] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Cemet] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Cemet] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Cemet] SET ARITHABORT OFF
GO
ALTER DATABASE [Cemet] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Cemet] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Cemet] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Cemet] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Cemet] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Cemet] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Cemet] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Cemet] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Cemet] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Cemet] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Cemet] SET  DISABLE_BROKER
GO
ALTER DATABASE [Cemet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Cemet] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Cemet] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Cemet] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Cemet] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Cemet] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Cemet] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Cemet] SET  READ_WRITE
GO
ALTER DATABASE [Cemet] SET RECOVERY FULL
GO
ALTER DATABASE [Cemet] SET  MULTI_USER
GO
ALTER DATABASE [Cemet] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Cemet] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'Cemet', N'ON'
GO
USE [Cemet]
GO
/****** Object:  Table [dbo].[Satuan]    Script Date: 12/02/2013 12:35:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Satuan](
	[SatuanId] [int] IDENTITY(1,1) NOT NULL,
	[Nama] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Satuan] PRIMARY KEY CLUSTERED 
(
	[SatuanId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Item]    Script Date: 12/02/2013 12:35:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[ItemId] [int] IDENTITY(1,1) NOT NULL,
	[Nama] [nvarchar](200) NOT NULL,
	[KodeSendiri] [nvarchar](200) NOT NULL,
	[Barcode] [nvarchar](200) NOT NULL,
	[Satuan_SatuanId] [int] NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_Item_Satuan]    Script Date: 12/02/2013 12:35:14 ******/
ALTER TABLE [dbo].[Item]  WITH CHECK ADD  CONSTRAINT [FK_Item_Satuan] FOREIGN KEY([Satuan_SatuanId])
REFERENCES [dbo].[Satuan] ([SatuanId])
GO
ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [FK_Item_Satuan]
GO

INSERT INTO SATUAN VALUES ('Kg');
INSERT INTO SATUAN VALUES ('Liter')
