//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemet.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string Nama { get; set; }
        public string KodeSendiri { get; set; }
        public string Barcode { get; set; }
        public int Satuan_SatuanId { get; set; }
    
        public virtual Satuan Satuan { get; set; }
    }
}
