//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemet.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satuan
    {
        public Satuan()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int SatuanId { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
